### ISSUE TITLE
Sweep: write a full python code to project the 3d point cloud data from ouster lidar into an image , we will do camera calibration and lidar camera calibration , after projecting lidar data to image we will make a car detection and tracking on image then get the location of the detected object from the lidar data by cropping the projected lidar data and get the average coordinates for it , and we will detect the speed of car by using the detected coordinated and time between frames , the lidar and camera are fixed above a moving car  

### ISSUE THREAD

**Issue by mos-ali** [sweepai/sweep#1264]
### Details

we have one ouster lidar fixed above a moving car and it covers 180 degree field of view and this lidar fixed in the middle of the car surface
we have also 3 cameras installed above the same moving car and each camera cover a part of the 180 degree field of view of the lidar and each camera cover a different part of the view
lidar is ouster lidar 32 channel 
we need to make a sensor fusion of the 3 camera and the lidar 
and project the lidar data into the 3 camera
make a car detection and tracking on the 3 camera and extract 3d point cloud data from the fused image
define detected car position from the lidar data and get the speed of the detected car 

### Files to change

```shell
src/car_detection.py
src/car_tracking.py
src/camera_calibration.py
src/ouster_lidar_calibration.py
src/sensor_fusion.py
src/car_postion.py
src/car_speed_detection.py
src/ouster_stream.py
src/camera_stream.py
src/realtime_speed_detection.py
```

<details>
<summary>Checklist</summary>

- [X] `src/car_detection.py`
> * Import necessary libraries for object detection.
> • Define a function for car detection that takes the fused image as input and outputs the detected cars.

- [X] `src/car_tracking.py`
> * Import necessary libraries for object tracking.
> • Define a function for car tracking that takes the detected cars and tracks them across frames.

- [X] `src/camera_calibration.py`
> * Import necessary libraries for camera calibration.
> • Define a function for camera calibration that calibrates the cameras.

- [ ] `src/ouster_lidar_calibration.py`
> * Import necessary libraries for lidar calibration.
> • Define a function for lidar calibration that calibrates the lidar.

- [ ] `src/sensor_fusion.py`
> * Import necessary libraries for sensor fusion.
> • Define a function for sensor fusion that fuses the data from the lidar and cameras.

- [ ] `src/car_postion.py`
> * Import necessary libraries for position estimation.
> • Define a function for car position estimation that estimates the position of the detected cars using the lidar data.

- [ ] `src/car_speed_detection.py`
> * Import necessary libraries for speed detection.
> • Define a function for car speed detection that estimates the speed of the detected cars using the position estimates and the time between frames.

- [ ] `src/ouster_stream.py`
> * Import necessary libraries for data streaming.
> • Define a function for ouster stream that handles the streaming of data from the ouster lidar.

- [ ] `src/camera_stream.py`
> * Import necessary libraries for data streaming.
> • Define a function for camera stream that handles the streaming of data from the cameras.

- [ ] `src/realtime_speed_detection.py`
> * Import necessary libraries for real-time speed detection.
> • Define a function for real-time speed detection that uses the car speed detection module to estimate the speed of cars in real-time.

</details>

**Comment by lukejagg** [comment]
Hey @mos-ali , this will create changes in our repo `sweepai/sweep`. If you would like to make changes to your own repo, please create an issue there!

Also, please note that Sweep is your personal junior developer, so it may not be suited for something as complex as this.

**Comment by mos-ali** [comment]
> 

hi @lukejagg  thanks for your comment , yes i know it is a little bit complex task but i want to check the ability of Sweep to do it or not and to collect some ideas about it and how can we will use it in the pro version

**Comment by kevinlu1248** [comment]
@mos-ali This isn't the type of problem we designed Sweep to solve. Sweep is intended to improve an existing codebase, not to start a project from scratch.
